syncplay/messages.py

Translated new stuff,
Fixed some Typos,
Made some Translations more straight-forward by moving away from word-by-word-translations

German Translation

---

syncplay/messages.py

Update German translation

---

syncplay/ui/ConfigurationGetter.py

changed the type, of file  in argparser so that files can accept unicode characters

change type, of file in ConfigurationGetter.py from str to utf-8

---

GNUmakefile

Support for DESTDIR and PREFIX

---

appdmg.py
buildInstaller.py
buildPy2app.py
buildPy2exe.py
syncplay/client.py
syncplay/clientManager.py
syncplay/constants.py
syncplay/messages.py
syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_it.py
syncplay/messages_ru.py
syncplay/players/__init__.py
syncplay/players/basePlayer.py
syncplay/players/mpc.py
syncplay/players/mpcbe.py
syncplay/players/mplayer.py
syncplay/players/mpv.py
syncplay/players/playerFactory.py
syncplay/players/vlc.py
syncplay/protocols.py
syncplay/server.py
syncplay/ui/ConfigurationGetter.py
syncplay/ui/GuiConfiguration.py
syncplay/ui/__init__.py
syncplay/ui/consoleUI.py
syncplay/ui/gui.py
syncplay/utils.py
syncplayClient.py
syncplayServer.py

Reverts Syncplay/syncplay#192 due some bugs caused by the refactoring in the tri-state logic: 
wrong file size in the UI, wrong OSD information (readiness and user number).

Revert "Code Syntax Refactoring"

---

GNUmakefile

Remove some odd locations for icons

---

syncplay/messages_de.py

Hello everyone,
I have just re-discovered this wonderful project and wanted to bring its German translation up to date. I have completed and removed the `TODO` notes and also replaced the straight single quotes (`'`) with correct German typographical quotes (`„“`).

German (de) translation update

---

syncplay/client.py

client: add simple wildcard matching mechanism for trusted domains

---

syncplay/ui/GuiConfiguration.py

Fixes #281 
There were two variables flipped around :P

Fixed font setting not being able to save

---

syncplay/messages_ru.py

I've translated all the missing messages into Russian and edited some of the old ones. Some further editing might be necessary to make the tone and terminology consistent.
Continuation of https://github.com/Syncplay/syncplay/pull/363.
Fixes https://github.com/Syncplay/syncplay/issues/361.
@Et0h

Update Russian translation

---

syncplay/messages_pt_BR.py

This PR keeps pt_BR translation up to date with all new strings and fixes a typo.

Update pt_BR translation, fix typo

---

.github/workflows/build.yml
ci/appimage-script.sh

Bundle libgthread-2.0.so.0 into AppImage

---

syncplay/constants.py
syncplay/players/mpc.py

(Also normalizes some Windows path constants to all be consistently lowercase)
Fixes #453

Support for LAV Filters Megamix

---

syncplay/server.py

This commit fixes some conditions as seems to be intended after the changes in c0e8652c8c2a94f3a75d67bd0798292c55527e32.
Currently it crashes because it refers to attributes/methods that were removed in the mentioned commit.

fix persistent rooms condition

---

syncplay/messages_pt_BR.py

Fixed some minor issues and translated missing lines.

Update PT-BR translation

---

buildPy2exe.py
syncplay/messages.py
syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_es.py
syncplay/messages_fr.py
syncplay/messages_it.py
syncplay/messages_pt_BR.py
syncplay/messages_pt_PT.py
syncplay/messages_ru.py
syncplay/messages_tr.py
syncplay/messages_zh_CN.py

Added Simplified Chinese Translation.

Added Simplified Chinese Translation.

---

syncplay/messages_fr.py

Add missed stub for commandList-notification/queueandselect

---

buildPy2exe.py
syncplay/messages.py
syncplay/messages_eo.py

Based on work from Tirifto contributed under Apache 2.0 license via email

Add Esperanto translation (by Tirifto)

---

syncplay/protocols.py

Trying to help debug #553 and similar connection issues.

Increase detail of connection errors

---

syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py

See https://github.com/Syncplay/syncplay/issues/571

Attempt to fix mpv quit error (#571)

---

syncplay/constants.py

Tested in Windows 11 vm
Installer for tests if needed: https://mega.nz/file/QNBEHJIA#OMiRK62O8no9gv_kAuEVrOhLKOrGKXUYdNQ33_fvxr8

constants: add new per-user mpv.net path

---

syncplay/messages_de.py

Fixed the message that is shown if the client doesn't support TLS (it was saying the server doesn't support TLS).
Also added not yet done translation.

Fixed German Translation and added more Translated Strings

---

syncplay/players/mpv.py

Pass input-ipc-server player argument to mpv (#529)

---

syncplay/messages_tr.py

Each #translate tagged line has been translated.

Update Turkish translation
