Syncplay/syncplay

.gitignore
syncplay/constants.py
syncplay/players/mpv.py

mpv finally dropped --slave-broken, so Syncplay on Windows needs this change to work.

Stop using --slave-broken

---

syncplay/constants.py
syncplay/players/mplayer.py
syncplay/players/mpv.py

This allows the per-player user arguments to overwrite
Syncplay's style defaults in mpv.
Be careful that, if you turn off force-window and idle, you have to
supply Syncplay with the filename before opening the video window.

Don't overwrite user arguments with our style defaults

---

syncplay/ui/gui.py

A picture (or screenshot) says more than a thousand words:
Now let's work on the other issues @Et0h [mentioned](https://github.com/Syncplay/syncplay/issues/81#issuecomment-162468488) in #81.

bugfix: display the menu bar in OS X

---

syncplay/ui/GuiConfiguration.py

This should be self-explanatory.

set the correct player executable path when an .app was selected on OS X (fixes #91)

---

resources/lua/intf/syncplay.lua

Hi,
this pull request fixes the Syncplay plugin for VLC 3.0.0.

VLC version 3.0.0 uses times in microseconds

---

syncplay/constants.py

scaletempo is also not useful with the small changes in playback rate from the slowing down in Syncplay. They're small enough to be more noticeable with it than without, like with interpolation+display-sync.
Besides, mpv has --audio-pitch-correction enabled by default which automatically adds scaletempo when needed.

mpv bugfixes

---

syncplay/ui/ConfigurationGetter.py

This prevents the import error message from being displayed when GUI is
disabled on systems without PySide
Additionally, remove some redundant conditionals

Try to setup GUI, iff noGui is False

---

syncplay/constants.py
syncplay/players/mpv.py

The 'length' property was deprecated since then and will be gone
with 0.23.0 and is already gone in git master, so Syncplay is
broken with it.

Support mpv without length property

---

syncplay/ui/ConfigurationGetter.py

Solves #116 and #60 (finally). 
Adds a new dependency: `appnope` [(GitHub)](https://github.com/minrk/appnope), required only on macOS. It is available on pip. If merged, I guess the installation instructions have to be updated accordingly.
(Note: please be patient if I did something horribly wrong since this is my first pull request.)

Prevents App Nap on macOS 10.9+

---

syncplay/ui/gui.py

As suggested by @Et0h , I added the flag `QtGui.QFileDialog.DontUseNativeDialog` on the two file dialogs that showed issues on macOS. This is not a real fix because the bug is probably in upstream PySide or Qt 4, but at least it allows to use all the file dialogs on this operative system too.

"Fixes" file dialogs on macOS

---

syncplay/ui/gui.py

On macOS, fixes the "Add to the bottom of shared playlist" QFIleDialog with the `QtGui.QFileDialog.DontUseNativeDialog` workaround used before. Also fixes drag and drop of media files on both the "List of who is playing what" and "Shared playlist" boxes.
Drawbacks: requires PyObjC. If merged, the installation instructions should be updated to include `pip install pyobjc`.

Fixes issue #146

---

buildPy2exe.py

Require NSIS >=3 for unicode support

buildPy2exe: Find installed NSIS through registry

---

buildPy2exe.py

buildPy2exe: use proper python2 name for winreg

---

buildPy2exe.py
syncplay/messages.py
syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_it.py
syncplay/messages_ru.py
syncplay/ui/GuiConfiguration.py
syncplay/ui/gui.py

The entire application and its installer have been translated into Italian.
A hard coded label in **_ui/GuiConfiguration.py_** has been replaced by a new label `chatoutputheader-label`. Thus, `self.chatOutputGroup = QtWidgets.QGroupBox(u"Chat message output")` is now `self.chatOutputGroup = QtWidgets.QGroupBox(getMessage("chatoutputheader-label"))`.
For clarity's sake, `chatoutputheader-label` has also been added to the others **messages_xx.py**

Supporting for Italian translation.

---

syncplay/ui/gui.py

This fixes the following error I'm seeing when I try to add URIs to the playlist on the current master version:
```
Traceback (most recent call last):
File "/home/user/Projects/syncplay/syncplay/ui/gui.py", line 628, in <lambda>
menu.addAction(QtGui.QPixmap(resourcespath + "world_add.png"), getMessage("addurlstoplaylist-menu-label"), lambda: self.OpenAddURIsToPlaylistDialog())
File "/home/user/Projects/syncplay/syncplay/ui/gui.py", line 382, in wrapper
return f(self, *args, **kwds)
File "/home/user/Projects/syncplay/syncplay/ui/gui.py", line 979, in OpenAddURIsToPlaylistDialog
URI = urllib.parse.unquote(URI)
File "/usr/lib64/python3.6/urllib/parse.py", line 610, in unquote
if '%' not in string:
TypeError: a bytes-like object is required, not 'str'
```

Remove obsolete encode/decode calls

---

syncplay/ui/ConfigurationGetter.py

Turns out I committed a slight standards compliance blunder in my XDG patch:
> If, when attempting to write a file, the destination directory is non-existant an attempt should be made to create it with permission 0700.
As per the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

Create XDG_CONFIG_HOME with safe permissions

---

syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_it.py
syncplay/messages_ru.py

Including this "tag" on any message, causes the client to strip multi-line messages received from server, basically only printing the first line. You can't for example see the server MOTD and a clientversion message at the same time (it only shows up the latter, not both). Client prints that <NOTICE> tag as it if were a nickname, so it makes sense to strip multi-line messages.

Remove NOTICE tag for clientversion messages

---

syncplay/server.py

Twisted version 16.6.0 and older don't support raiseMinimumTo argument in CertificateOptions. This allows TLS to work on distributions like Debian Stretch (current stable) and Ubuntu 16.04 LTS.

Workaround for older twisted versions which don't support raiseMinimumTo.

---

requirements.txt

Changing "zope.inteface" to "zope.interface" for dependencies installation.
It's a misspell-problem when I try compiling the source code.

Misspell: change "inteface" to "interface"

---

buildPy2exe.py
syncplay/client.py
syncplay/ui/GuiConfiguration.py

From the Python 3.8 [changelog](https://docs.python.org/3/whatsnew/3.8.html#changes-in-python-behavior):
> The compiler now produces a SyntaxWarning when identity checks (is and is not) are used with certain types of literals (e.g. strings, numbers). These can often work by accident in CPython, but are not guaranteed by the language spec. The warning advises users to use equality tests (== and !=) instead.

Fix string equality checks

---

.travis.yml
travis/macos-deploy.sh
travis/macos-install.sh

Deploys appear to be failing due to an issue with Travis installing it's dpl gem. Others (https://travis-ci.community/t/ruby-openssl-python-deployment-fails-on-osx-image/6753) have had the same problem, and this is a workaround from there that should probably work but is hard to check until it's on master.

Fixes for OSX deploy issues

---

travis/macos-deploy.sh

So it turns out the workaround hack in #275 isn't needed any more, probably due to the homebrew changes there restricting the alterations to the filesystem. https://travis-ci.org/github/palfrey/syncplay/jobs/665559940 demos a upload being done, and other than it failing due to authorisation issues (which hopefully are just due to it being on my fork, not the main repo) it should hopefully work now!

Remove ruby reinstall workaround for openssl, as not needed

---

syncplay/ui/GuiConfiguration.py

/usr/lib/syncplay/syncplay/ui/GuiConfiguration.py:323: SyntaxWarning: "is not" with a literal. Did you mean "!="?

fix warning message

---

syncplay/resources/syncplayintf.lua

In mpv-player/mpv@07287262513c0d1ea46b7beaf100e73f2008295f, a strcmp on
the previously displayed and the new text has been removed, causing
excessive GPU usage especially on idle frames when playback was paused.
I will submit a patch to upstream, but mpv versions 0.31 & 0.32 are
already affected by this.
See torque/mpv-progressbar#56 for a similar report to a different
script.
Note: This is *just* the quick fix for the preformance regression. I'll submit usage of the new API in separate PR as it would bump the minium required mpv version.

Work around performance regression in mpv's osd

---

buildPy2exe.py
syncplay/messages.py
syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_es.py
syncplay/messages_it.py
syncplay/messages_pt_BR.py
syncplay/messages_ru.py

Add new 'pt_BR' language to 'language-argument'

Add Brazilian Portuguese translation

---

syncplay/constants.py
syncplay/players/mpv.py
syncplay/players/mpvnet.py
syncplay/players/python_mpv_jsonipc/LICENSE.md
syncplay/players/python_mpv_jsonipc/README.md
syncplay/players/python_mpv_jsonipc/docs.md
syncplay/players/python_mpv_jsonipc/python_mpv_jsonipc.py
syncplay/players/python_mpv_jsonipc/setup.py
syncplay/resources/syncplayintf.lua
syncplay/resources/third-party-notices.rtf

This should allow Syncplay to support mpv >0.30.0. Raises minimum mpv version to >= 0.17.0.
Many thanks to @iwalton3 for his Python MPV JSONIPC library which is available from https://github.com/iwalton3/python-mpv-jsonipc/

Move to JSON IPC API for mpv using iwaltons3's library (#261)

---

syncplay/client.py

This is more robust.
The old code had a mistake as well, which is very embarrassing.

client: actually fix the wildcard matching

---

syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_es.py
syncplay/messages_it.py
syncplay/messages_ru.py
syncplay/protocols.py

When I was trying to make syncplay working with a self-signed certificate I had a reconnection loop.
The issue was related to the SAN (Subject Alternative Name) that was not correct in my certificate.
I think it can be usefull to detect this error.

Add error message if SAN doesn't match hostname

---

syncplay/client.py
syncplay/players/mpc.py

Noticed that when I try to sync YouTube videos on MPC with `youtube-dl`.
If the video title contains emojis it starts disconnecting and reconnecting infinetely. 
Stacktrace:
```Unhandled Error
Traceback (most recent call last):
File "C:\Users\VIKTOR\AppData\Local\Programs\Python\Python38\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
return callWithContext({"system": lp}, func, *args, **kw)
File "C:\Users\VIKTOR\AppData\Local\Programs\Python\Python38\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
return context.call({ILogContext: newCtx}, func, *args, **kw)
File "C:\Users\VIKTOR\AppData\Local\Programs\Python\Python38\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
return self.currentContext().callWithContext(ctx, …
```

Fixed crashes when trying to open YouTube videos with emojis

---

syncplay/players/mpv.py

Allow MPV users to set a custom socket via __input-ipc-server__ flag. This will make possible simultaneous use of Syncplay and other tools like SVP-project

MPV: Add the possibility to control which socket to use

---

buildPy2exe.py
syncplay/messages.py
syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_es.py
syncplay/messages_it.py
syncplay/messages_pt_BR.py
syncplay/messages_pt_PT.py
syncplay/messages_ru.py
syncplay/messages_tr.py

I could not understand how to add language option to the project codes. But I translated messages to Turkish from English.

Turkish language translations added

---

GNUmakefile

If it doesn't exist first, `hicolor` will be stripped from the path by the `cp` command

Create icons folder if it doesn't exist

---

syncplay/players/mpv.py
syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py

This is a follow-up to #279. In principle, this issue should have been solved in https://github.com/Syncplay/syncplay/commit/c07206c18992c1dca401b30a01b9f0fe54a71df5 and #360. However, a mixture of changes in the way Homebrew installs `youtube-dl`, plus a mistake in which the environment was (not) transferred to the relevant subprocess, still caused it to show up in 1.6.7.
This PR re-enables the environment patching on macOS and, additionally, slightly modifies how the environment is patched to make this functional also on the arm64 architecture. Credits to @cordelac for having tested this on their machine.
Please test if this affects running mpv on Windows and Linux in any way before merging.
Closes: #379

Re-enable youtube-dl on macOS plus mpv and IINA

---

syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py
syncplay/vendor/python_mpv_jsonipc/setup.py

Update to version 1.1.13 to hopefully address #322 fully.

Update mpv json ipc vendor code

---

buildPy2exe.py

If LANG parameter set, don't show language dialog.
Fixes #396 & #358
This can allow fully automatic installation via chocolatey.
Example usage: `.\Syncplay-X.X.X-Setup.exe /S /LANG=1033`

Add LANG Parameter

---

syncplay/client.py
syncplay/constants.py
syncplay/ui/gui.py
syncplay/utils.py

**TL;DR:** If you want to trust URIs with credentials in them, you have to add the full thing to the trusted domains: `user:pass@example.com`. This PR makes it so you can just add `example.com`, even when using credentials.
**Long version**
I have the following use-case: I have a webserver that serves videos, but they are protected with HTTP basic authentication. It is possible to embed the credentials in a URL like so:
`https://username:password@example.com/video.mkv`
This URL works, for example, in mpv. I can add this URL in the syncplay playlist and it works fine. But I get the untrusted domain warning and have to click the playlist entry manually. If I add `example.com` to the "trusted domains" in the Advanced menu, I still get the warning. Only if I add …

Trusted Domains: Allow trusting a domain regardless of HTTP basic auth credentials

---

docs/syncplay-server.1
syncplay/ep_server.py
syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_es.py
syncplay/messages_it.py
syncplay/messages_pt_BR.py
syncplay/messages_pt_PT.py
syncplay/messages_ru.py
syncplay/messages_tr.py
syncplay/server.py

Added the **--rooms-dir [directory]** option to the server.
This allows the specifying of a directory to be used to read and write room data in order for playlists to persist permanently, regardless of every watcher leaving or the server restarting.
The behavior won't take place if the directory does not exist, or if the **--isolate-rooms** option is enabled.

Added room permanence option to server

---

docs/syncplay-server.1

The current documentation specifies directories, likely as a result of the original design before use of a database, but the arguments expect files. This simply clarifies the documentation to match the code itself.

Correct persistance argument type

---

syncplay/utils.py

if condition was false convertMultilineStringToList returned "" instead
of an empty list.

Fixes converting lines to array

---

syncplay/client.py
syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_es.py
syncplay/messages_fr.py
syncplay/messages_it.py
syncplay/messages_pt_BR.py
syncplay/messages_pt_PT.py
syncplay/messages_ru.py
syncplay/messages_tr.py
syncplay/messages_zh_CN.py

I would like to use Syncplay to watch a movie with a friend for a podcast where we watch together, pause to talk about things, and assemble it into a slide slow later. Syncplay printing when the media was paused in its log would help with this immensely.

Print timestamp when pausing.

---

syncplay/constants.py
syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_es.py
syncplay/messages_fr.py
syncplay/messages_it.py
syncplay/messages_pt_BR.py
syncplay/messages_pt_PT.py
syncplay/messages_ru.py
syncplay/messages_tr.py
syncplay/messages_zh_CN.py
syncplay/ui/consoleUI.py

/next, /qn command to load next file in playlist. I find it useful for me, hence the proposal

Add /next command

---

buildPy2exe.py
syncplay/messages_de.py
syncplay/messages_en.py
syncplay/messages_eo.py
syncplay/messages_es.py
syncplay/messages_fr.py
syncplay/messages_it.py
syncplay/messages_pt_BR.py
syncplay/messages_pt_PT.py
syncplay/messages_ru.py
syncplay/messages_tr.py
syncplay/messages_zh_CN.py

This refactor moves the message files from buildPy2Exe.py to the respective messages_*.py files for the languages.
Benefits:
* Easier to maintain those languages as all the text is in the same place.
* Simplifies the process of adding new languages to Syncplay (and of creating any guides to explain how to do this).
* Makes it easier for any future move to services such as Weblate as per #550

Refactor: Move installer text to messages_ files

---

syncplay/messages_fi.py

I am performing `code --diff messages_fi.py messages_en.py` and attempting to correct what I see wrong with #561.
I am not able to correct everything or see some parts aren't great, so other localizers would be welcome. I am also taking liberties especially where I just don't see a way for the English wording working translated directly.

[WIP] Correct Finnish localizations

---

syncplay/utils.py

This should fix errors such as:
>  File "syncplay\players\mpv.pyc", line 743, in actuallySendLine
>     File "syncplay\client.pyc", line 1626, in showDebugMessage
> builtins.UnicodeEncodeError: 'charmap' codec can't encode character '\u3009' in position 684: character maps to <undefined>
When using Syncplay with mpv and--debug mode on Windows.

Log --debug as UTF-8 to fix charmap mapping

---

syncplay/client.py

This change should mean that if someone specifies *.example.com as a trusted domain then abc.example.com will be recognised as a trusted domain. See #587 and #437.

Add wildcard matching of trusted subdomains (#587)

---

syncplay/client.py

Address the issue raised in #567 where, if you were the only one in the room when you were disconnected, the shared playlist is empty for everyone else after reconnection until something is added/removed from the playlist.

Restore server-side playlist on reconnect (#567)

---

syncplay/ui/ConfigurationGetter.py

Hi,
I've been using Wayland lately and I've noticed that the SyncPlay icon doesn't appear in Wayland:
According to Wayland guidelines, `setWindowIcon()` no longer works on Wayland and the new way of doing is is to reference the name of the .desktop file through the `QGuiApplication::setDesktopFileName()` function:
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon
I added the required line in ConfigurationGetter.py since that's where the `QApplication` gets created, please tell me if you'd like it elsewhere. This change fixes the icon in Wayland:
I used "syncplay" since that's how the .desktop file is called, but the guidelines suggest the desktop file should named in a reverse DNS style, but that's up to you.
Cheers.

Define desktop filename for Wayland compliance (fixes icon)

---

syncplay/ui/ConfigurationGetter.py

`SafeConfigParser` was renamed to `ConfigParser` ([docs](https://docs.python.org/3.12/whatsnew/3.12.html?highlight=safeconfigparser#configparser))
`.readfp()` was renamed to `.read_file()` ([docs](https://docs.python.org/3.12/library/configparser.html?highlight=readfp#configparser.ConfigParser.read_file))
Otherwise trying to run the client with python 3.12 gets you this nice error
```
> python syncplayClient.py
Traceback (most recent call last):
File "[]/syncplay/syncplayClient.py", line 14, in <module>
from syncplay import ep_client
File "[]/syncplay/syncplay/ep_client.py", line 3, in <module>
from syncplay.clientManager import SyncplayClientManager
File "[]/syncplay/clientManager.py", line 4, in <module>
from syncplay.ui.ConfigurationGetter import ConfigurationGetter
File …
```

Update to python 3.12

---

syncplay/ui/GuiConfiguration.py

Qt.AlignTop & Qt.AlignLeft is 0, so we might as well not call setAlignment() at all.

Remove broken setAlignment() calls

---

syncplay/ui/GuiConfiguration.py
syncplay/ui/gui.py

Don't pass empty model to QCompleter

---

requirements_gui.txt

PySide2 is dead and won't support Python 3.12 or newer.

Use PySide6 for non-windows + python >= 3.12

---

syncplay/constants.py
syncplay/players/vlc.py
syncplay/ui/GuiConfiguration.py
syncplay/utils.py

Hopefully this will fix the VLC issue #665 raised by @zuluwi and also work for other players.

Allow player arguments with spaces/quotes (#665)

---

syncplay/players/mpv.py
syncplay/utils.py

Fixes #674
I haven't tested on Windows or MacOS.

Fix MPV socket getting created in CWD

---

syncplay/constants.py
syncplay/utils.py

```
/usr/lib/syncplay/syncplay/utils.py:330: SyntaxWarning: invalid escape sequence '\g'
return re.sub(constants.ROOM_NAME_STRIP_REGEX, "\g<roomnamebase>", RoomName)
/usr/lib/syncplay/syncplay/utils.py:508: SyntaxWarning: invalid escape sequence '\+'
CONTROLLED_ROOM_REGEX = re.compile("^\+(.*):(\w{12})$")
/usr/lib/syncplay/syncplay/utils.py:509: SyntaxWarning: invalid escape sequence '\d'
PASSWORD_REGEX = re.compile("[A-Z]{2}-\d{3}-\d{3}")
/usr/lib/syncplay/syncplay/constants.py:115: SyntaxWarning: invalid escape sequence '\.'
FILENAME_STRIP_REGEX = "[-~_\.\[\](): ]"
/usr/lib/syncplay/syncplay/constants.py:116: SyntaxWarning: invalid escape sequence '\-'
CONTROL_PASSWORD_STRIP_REGEX = "[^a-zA-Z0-9\-]"
/usr/lib/syncplay/syncplay/constants.py:117: SyntaxWarning: invalid escape sequence '\+' …
```

Fix invalid string escapes

---

syncplay/ui/gui.py

This looks much better when using PySide6 6.7.2.

Adjust QSplitter style

---

.github/workflows/build.yml

https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Migrate to actions/upload-artifact@v4

---

syncplay/client.py
syncplay/protocols.py
syncplay/ui/consoleUI.py
syncplay/ui/gui.py

Hello, for a MOTD it is natural to use ASCII art but since messages in the chat box are added using QT's HTML-like text fragments, multiple spaces are merged together and the default variable-width font destroys alignment.
<table>
<tr>
<td>default look:</td>
<td>desired look:</td>
</tr><tr><td>
</td><td>
</td></tr></table>
Therefore, I propose that when showing a MOTD we escape spaces with `&nbsp;` and wrap everything in `<code>` tags to select a monospace font.
One problem is that MOTD is also used for showing warnings to the user, such as the "new-syncplay-available-motd-message" message. These will also be changed accordingly. If undesired, these warning should be sent in a separate field.
I have only tested this on openSUSE with python 3.11.11 and PySide6 6.8.0.2 so far. I assume that …

Special-case MOTD in showMessage procedures.

---

syncplay/protocols.py

As mentioned in the #725 , moving the persistent rooms notice above the MOTD can reduce the distraction for users reading the MOTD.

Move persistent rooms notice above MOTD
